- name: Hostgroups - Set Default Root Password
  hosts: satellites
  gather_facts: no
  vars_files:
    - vars/hostgroups.yml

  tasks:
    - name: Host Groups - Set Default Root Password
      redhat.satellite.hostgroup:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ inventory_hostname }}"
        organization: "{{ satellite_organization }}"
        name: "{{ item.name }}"
        root_pass: "{{ hostgroup_default_root_password }}"
        state: present
      loop: "{{ hostgroups }}"

