---
- name: Install Capsule Packages
  hosts: capsules
  gather_facts: false

  tasks:
    - name: Install Capsule Packages
      ansible.builtin.package:
        name:
#          - satellite-capsule
          - chrony
          - sos
          - bash-completion
          - tree
          - vim-enhanced
        state: present

    - name: Download the Satellite 6 Queue Checker script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/jasondickerson/sat6-queue-check/master/sat6-queue-check.bash
        dest: /root/sat6-queue-check.bash
        mode: '0750'
