---
- name: Configure Firewall and Install Satellite
  hosts: satellites
  gather_facts: false

  tasks:
    - name: Configure Satellite Firewall Rules
      ansible.builtin.import_role:
        name: redhat.rhel_system_roles.firewall
      tags:
        - firewall

    - name: Run Satellite Installer
      ansible.builtin.import_role:
        name: redhat.satellite_operations.installer
      tags:
        - satellite_installer
