---
- name: Manage Sync Plans
  hosts: satellites
  gather_facts: false
  tags:
    - syncplans
    - satconfig

  tasks:
    - name: Manage Sync Plans
      ansible.builtin.import_role:
        name: redhat.satellite.sync_plans
