---
- name: Maintain Activation Keys
  hosts: satellites
  gather_facts: false
  vars_files:
    - vars/actkeys.yml

  roles:
    - role: redhat.satellite.activation_keys
      vars:
        satellite_server_url: "https://{{ inventory_hostname }}"
        satellite_activation_keys: "{{ activation_keys }}"
      tags: actkeys
