---
- name: Manage Content Content Views
  hosts: satellites
  gather_facts: false
  tags:
    - satconfig

  tasks:
    - name: Manage Lifecycle Environments
      ansible.builtin.import_role:
        name: redhat.satellite.lifecycle_environments
      tags:
        - lifecycles

    - name: Manage Content Views
      redhat.satellite.content_view:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_server_url }}"
        organization: "{{ satellite_organization }}"
        name: "{{ item.name }}"
        repositories: "{{ item.repositories }}"
        auto_publish: "{{ item.auto_publish }}"
        solve_dependencies: "{{ item.solve_dependencies }}"
        composite: "{{ item.composite }}"
      loop: "{{ content_views }}"
      tags:
        - cvs

    - name: Publish Content Views and Promote to Lifecycle Environments
      redhat.satellite.content_view_version:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_server_url }}"
        content_view: "{{ item.name }}"
        organization: "{{ satellite_organization }}"
        lifecycle_environments: "{{ item.lce }}"
      loop: "{{ content_views }}"
      tags:
        - pubpromote
