---
- name: Maintain Satellite Repositories
  hosts: satellites
  gather_facts: false
  tags:
    - satconfig

  tasks:
    - name: Refresh manifest
      redhat.satellite.subscription_manifest:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_server_url }}"
        organization: "{{ satellite_organization }}"
        state: refreshed
      tags:
        - manifest

    - name: Manage GPG keys
      redhat.satellite.content_credential:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_server_url }}"
        organization: "{{ satellite_organization }}"
        content_type: gpg_key
        name: "{{ item.gpg_key }}"
        content: "{{ lookup('url', item.gpg_url) }}"
      loop: "{{ satellite_products }}"
      when: item.gpg_key is defined
      tags:
        - gpgkeys

    - name: Enable repositories
      ansible.builtin.import_role:
        name: redhat.satellite.repositories
      tags:
        - enablerepos

    - name: Sync Products
      redhat.satellite.repository_sync:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_server_url }}"
        product: "{{ item.name }}"
        organization: "{{ satellite_organization }}"
      loop: "{{ satellite_products }}"
      tags:
        - sync
