---
- name: Manage Activation Keys
  hosts: satellites
  gather_facts: false
  tags:
    - actkeys
    - satconfig

  tasks:
    - name: Manage Activation Keys
      ansible.builtin.import_role:
        name: redhat.satellite.activation_keys
