---
- name: Manage Provisioning
  hosts: satellites
  gather_facts: false
  tags:
    - satconfig
    - provision

  tasks:
    - name: Manage Domains
      ansible.builtin.import_role:
        name: redhat.satellite.domains
      tags:
        - domains

    - name: Manage Subnets
      ansible.builtin.import_role:
        name: redhat.satellite.subnets
      tags:
        - subnets

    - name: Manage Hostgroups
      ansible.builtin.import_role:
        name: redhat.satellite.hostgroups
      tags:
        - hostgroups

    - name: Set Default Root Password for Hostgroups
      redhat.satellite.hostgroup:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_server_url }}"
        organization: "{{ satellite_organization }}"
        name: "{{ item.name }}"
        root_pass: "{{ hostgroup_default_root_password }}"
        state: present
      loop: "{{ satellite_hostgroups }}"
      tags:
        - setrootpw
