---
products:
  - name: Red Hat Software Collections (for RHEL Server)
    repository_sets:
      ## RHEL 6 is no longer supported
      # - name: Red Hat Software Collections RPMs for Red Hat Enterprise Linux 6 Server
      #   basearch: x86_64
      #   releasever: 6Server
      - name: Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server
        basearch: x86_64
        releasever: 7Server
  - name: Red Hat Enterprise Linux Server
    repository_sets:
      ## RHEL 6 is no longer supported
      # - name: Red Hat Enterprise Linux 6 Server (Kickstart)
      #   basearch: x86_64
      #   releasever: "6.10"
      # - name: Red Hat Enterprise Linux 6 Server - Optional (RPMs)
      #   basearch: x86_64
      #   releasever: 6Server
      # - name: Red Hat Enterprise Linux 6 Server - Supplementary (RPMs)
      #   basearch: x86_64
      #   releasever: 6Server
      # - name: Red Hat Enterprise Linux 6 Server (RPMs)
      #   basearch: x86_64
      #   releasever: 6Server
      # - name: Red Hat Enterprise Linux 6 Server - Extras (RPMs)
      #   basearch: x86_64
      # - name: Red Hat Satellite Tools 6.8 (for RHEL 6 Server) (RPMs)
      #   basearch: x86_64
      - name: Red Hat Enterprise Linux 7 Server (Kickstart)
        basearch: x86_64
        releasever: 7.9
      - name: Red Hat Enterprise Linux 7 Server - Optional (RPMs)
        basearch: x86_64
        releasever: 7Server
      - name: Red Hat Enterprise Linux 7 Server - Supplementary (RPMs)
        basearch: x86_64
        releasever: 7Server
      - name: Red Hat Enterprise Linux 7 Server (RPMs)
        basearch: x86_64
        releasever: 7Server
      - name: Red Hat Enterprise Linux 7 Server - Extras (RPMs)
        basearch: x86_64
      - name: Red Hat Satellite Client 6 (for RHEL 7 Server) (RPMs)
        basearch: x86_64
  - name: Red Hat Enterprise Linux for x86_64
    repository_sets:
      - name: Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
        releasever: 8
      - name: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
        releasever: 8
      - name: Red Hat Enterprise Linux 8 for x86_64 - Supplementary (RPMs)
        releasever: 8
      - name: Red Hat Enterprise Linux 8 for x86_64 - AppStream (Kickstart)
        releasever: 8.9
      - name: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (Kickstart)
        releasever: 8.9
      - name: Red Hat Satellite Client 6 for RHEL 8 x86_64 (RPMs)
      - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)
        releasever: 9
      - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)
        releasever: 9
      - name: Red Hat Enterprise Linux 9 for x86_64 - Supplementary (RPMs)
        releasever: 9
      - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream (Kickstart)
        releasever: 9.3
      - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS (Kickstart)
        releasever: 9.3
      - name: Red Hat Satellite Client 6 for RHEL 9 x86_64 (RPMs)
      ## Example of how to bring in the Red Hat Satellite Capsule repository
      - name: Red Hat Satellite Maintenance 6.14 for RHEL 8 x86_64 (RPMs)
      - name: Red Hat Satellite Utils 6.14 for RHEL 8 x86_64 (RPMs)
  - name: "Red Hat CodeReady Linux Builder for x86_64"
    repository_sets:
      - name: "Red Hat CodeReady Linux Builder for RHEL 8 x86_64 (RPMs)"
        releasever: 8
      - name: "Red Hat CodeReady Linux Builder for RHEL 9 x86_64 (RPMs)"
        releasever: 9
  ## Ansible Engine has been replaced by Ansible core available from appstream repos on RHEL 8 and 9
  # - name: Red Hat Ansible Engine
  #   repository_sets:
  #     - name: Red Hat Ansible Engine 2.9 RPMs for Red Hat Enterprise Linux 7 Server
  #       basearch: x86_64
  ## Example of how to bring in the Red Hat Satellite Capsule repository
  # - name: Red Hat Satellite Capsule
  #   repository_sets:
  #     - name: Red Hat Satellite Capsule 6.14 for RHEL 8 x86_64 (RPMs)
  #       basearch: x86_64
  ## RHEL 6 is no longer supported
  ## Example of how to bring in Developer Toolset repos
  # - name: Red Hat Developer Toolset (for RHEL Server)
  #   repository_sets:
  #     - name: Red Hat Developer Toolset 2 RPMs for Red Hat Enterprise Linux 6 Server
  #       releasever: 6Server
  #       basearch: x86_64
  #     - name: Red Hat Developer Toolset RPMs for Red Hat Enterprise Linux 6 Server
  #       releasever: 6Server
  #       basearch: x86_64
  ## Example of EPEL 6
  # - name: "EPEL 6"
  #   label: "epel-6"
  #   gpg_key: "EPEL 6 GPG"
  #   gpg_url: https://archives.fedoraproject.org/pub/archive/epel/RPM-GPG-KEY-EPEL
  #   repositories:
  #     - name: "EPEL 6"
  #       label: "epel-6"
  #       content_type: yum
  #       url: https://archives.fedoraproject.org/pub/archive/epel/6/x86_64/
  - name: "EPEL 7"
    label: "EPEL_7"
    gpg_key: "EPEL 7 GPG"
    gpg_url: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    repositories:
      - name: "EPEL 7"
        label: "EPEL_7"
        content_type: yum
        url: https://dl.fedoraproject.org/pub/epel/7/x86_64/
  - name: "EPEL 8"
    label: "EPEL_8"
    gpg_key: "EPEL 8 GPG"
    gpg_url: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
    repositories:
      - name: "EPEL 8"
        label: "EPEL_8"
        content_type: yum
        url: https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/
      - name: "EPEL Modular 8"
        label: " EPEL_Modular_8"
        content_type: yum
        url: https://dl.fedoraproject.org/pub/epel/8/Modular/x86_64/
  - name: "EPEL 9"
    label: "EPEL_9"
    gpg_key: "EPEL 9 GPG"
    gpg_url: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
    repositories:
      - name: "EPEL 9"
        label: "EPEL_9"
        content_type: yum
        url: https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/
## Example of importing OVAL files for OpenSCAP
#  - name: "OVAL Files"
#    label: "OVAL_Files"
#    repositories:
#      - name: "Red Hat OVAL Files"
#        label: "Red_Hat_OVAL_Files"
#        content_type: file
#        url: https://www.redhat.com/security/data/oval/
## Puppet support will be removed in future versions of Red Hat Satellite
#  - name: "PuppetLabs"
#    label: "PuppetLabs"
#    repositories:
#      - name: "PuppetLabs_repo"
#        label: "PuppetLabs_repo"
#        content_type: puppet
#        url: https://forge.puppetlabs.com
  - name: Red Hat Ansible Automation Platform
    repository_sets:
      # - name: Red Hat Ansible Automation Platform 2.4 for RHEL 8 x86_64 (RPMs)
      - name: Red Hat Ansible Automation Platform 2.4 for RHEL 9 x86_64 (RPMs)
  ## Example of how to bring in the Red Hat Satellite Capsule repository
  - name: Red Hat Satellite Capsule
    repository_sets:
      - name: Red Hat Satellite Capsule 6.14 for RHEL 8 x86_64 (RPMs)
  # - name: Red Hat Enterprise Linux Server - Extended Life Cycle Support
  #   repository_sets:
  #     - name: Red Hat Enterprise Linux 5 Server - Extended Life Cycle Support (RPMs)
  #       basearch: x86_64
  #     # - name: Red Hat Enterprise Linux 6 Server - Extended Life Cycle Support - Optional (RPMs)
  #     #   basearch: i386
  #     - name: Red Hat Enterprise Linux 6 Server - Extended Life Cycle Support - Optional (RPMs)
  #       basearch: x86_64
  #     # - name: Red Hat Enterprise Linux 6 Server - Extended Life Cycle Support (RPMs)
  #     #   basearch: i386
  #     - name: Red Hat Enterprise Linux 6 Server - Extended Life Cycle Support (RPMs)
  #       basearch: x86_64
  #     - name: Red Hat Satellite Tools 6.8 (for RHEL 5 Server - ELS) (RPMs)
  #       basearch: x86_64
  #     # - name: Red Hat Satellite Client 6 (for RHEL 6 Server - ELS) (RPMs)
  #     #   basearch: i386
  #     - name: Red Hat Satellite Client 6 (for RHEL 6 Server - ELS) (RPMs)
  #       basearch: x86_64
  # - name: Red Hat Enterprise Linux High Availability for x86_64
  #   repository_sets:
  #     - name: Red Hat Enterprise Linux 8 for x86_64 - High Availability (RPMs)
  #       releasever: 8
  #     - name: Red Hat Enterprise Linux 9 for x86_64 - High Availability (RPMs)
  #       releasever: 9
  #     - name: Red Hat Enterprise Linux High Availability (for RHEL 6 Server) (RPMs)
  #       basearch: x86_64
  #       releasever: 6Server
  #     - name: Red Hat Enterprise Linux High Availability (for RHEL 7 Server) (RPMs)
  #       basearch: x86_64
  #       releasever: 7Server
  # - name: Red Hat Enterprise Linux Resilient Storage for x86_64
  #   repository_sets:
  #     - name: Red Hat Enterprise Linux Resilient Storage (for RHEL 6 Server) (RPMs)
  #       basearch: x86_64
  #       releasever: 6Server
  #     - name: Red Hat Enterprise Linux Resilient Storage (for RHEL 7 Server) (RPMs)
  #       basearch: x86_64
  #       releasever: 7Server
  #     - name: Red Hat Enterprise Linux 8 for x86_64 - Resilient Storage (RPMs)
  #       releasever: 8
  #     - name: Red Hat Enterprise Linux 9 for x86_64 - Resilient Storage (RPMs)
  #       releasever: 9
